
export const ActionType ={
    UPCOMING_USERS_SUCCESS: 'UPCOMING_USERS_SUCCESS',
    POSTS_USERS_SUCCESS: 'POSTS_USERS_SUCCESS',
    MAP_DATA_SUCCESS: 'MAP_DATA_SUCCESS',
    TIMELINE_DATA_SUCCESS: 'TIMELINE_DATA_SUCCESS'
}
